### ISSUE TITLE
please provide a command line tool

### ISSUE THREAD

**Issue by EricDeveaud** [adamhockenberry/bacphlip-py#3]
Hello, 

I was asked to install bacphlip on our cluster, can you please provide a command line tool that will be directly callable ? 

something like 
`backphlip -i pat2fasta_genome`

instead of 

`python -m backphlip -i pat2fasta_genome`

NB I curently installed bacphlip with a wrapper to provide such command line tool.

as a side effect this may helps adoption of your tool and inclusion in some distribution

regards

Eric

**Comment by adamhockenberry** [comment]
Thanks for the suggestion. Out of curiosity, why do you think it's advantageous to have a strict command-line interface rather than the pythonic command-line command? 

Asking simply because I don't know and would love some feedback. My initial instinct was to make the tool completely command-line only just as you suggest. But as I started diving into putting it on PyPi and making it installable with "pip",  it seemed like there were advantages of making it a library with callable functions that can still have the command line interface that just requires the "python -m" leader string.

I'm not opposed to adding the ability to call it directly as you suggest if there are perks of doing so, just don't know what advantages that provides. Or quite frankly, the changes that would be necessary to make (although I'm sure I can figure it out). Were it not on pip like it currently is, I was just going to say clone the repo and add the bacphlip directory to your path but thought that putting it on pip would actually increase adoption rather than asking folks to clone? Any feedback you have that I might not have thought about would be appreciated! And thanks again

**Comment by EricDeveaud** [comment]
having command line tool allows users to directly have the analysis done, and having the python module allows advanced user to perform the same task, plus perform some internal manipulation and introspection on their datas

command line tools faciltate embeding the tool on pipelines.

and last, we tend to provide different versions of python on our cluster, with just the standard lib installed ie whithout any external modules: users do pip install --user for external modules
we had some problems with python modules installed with one version of python, not working with another python even with minor versions differences. (not so surprising)

there is some python modules (eg htseq among many others) that provides command line tools. so adding this feature won't break the pip state of art ;-)

regards

Eric

**Comment by adamhockenberry** [comment]
Believe that I figured out how to make it a command-line tool that is directly callable rather than having to do the "python -m ..." stuff so closing the issue.

In v0.9.4 (not a tagged release) this should work:
"$ bacphlip -i /path/to/genome.fasta"

and I've actually removed "python -m ..." from the docs as I probably agree folks are more likely to call it in this direct command line manner. Library functionality is still there for those folks wishing to import individual functions.
