### ISSUE TITLE
Dependent on version scikit-learn 0.23.1?

### ISSUE THREAD

**Issue by sgsutcliffe** [adamhockenberry/bacphlip-py#7]
Thanks for developing this tool. I'm trying to install it on my HPC but our staff skipped version 0.23.1, so we have 0.23.2, 0.23.0.

I am in contact with them about compiling this version of scikit-learn. But I was wondering if newer versions might be supported as well?

**Comment by sgsutcliffe** [comment]
My issue installing scikit-learn was entirely a mistake on my end!

**Comment by adamhockenberry** [comment]
Great! If you have any more issues let me know, I'm going to try and keep up with "major" scikit-learn updates. So far in my experience none of the updates have broken anything but their docs say that if you save a model file in one version and reload it in another that there are no guarantees of compatibility which is why I was strict on required dependencies regarding the version. I've updated bacphlip now on about 4 or 5 different versions and it keeps on working without any issues so it's probably going to be rare that something internal changes within scikit-learn that breaks they way it reads from old models but it's still something I'm trying to keep an eye on and be cautious about. In general though I think any remotely up-to-date version should be totally okay.
